// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYWsNbc0I9_SqrO87yWkTPETpqtg3Efb0',
    appId: '1:23625991695:web:20053ee3b001cd7fe3c57a',
    messagingSenderId: '23625991695',
    projectId: 'hrms-app-c251b',
    authDomain: 'hrms-app-c251b.firebaseapp.com',
    storageBucket: 'hrms-app-c251b.firebasestorage.app',
    measurementId: 'G-V4PKRKS3MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKaKnqPSQXNs4Yum-RGTs2_Ub0UyfAUA',
    appId: '1:23625991695:android:3a38957d7895305de3c57a',
    messagingSenderId: '23625991695',
    projectId: 'hrms-app-c251b',
    storageBucket: 'hrms-app-c251b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwNMIr2ORfY-3xTdT7JxoKTrDw0FrsiA0',
    appId: '1:23625991695:ios:c5e761ba3660b18de3c57a',
    messagingSenderId: '23625991695',
    projectId: 'hrms-app-c251b',
    storageBucket: 'hrms-app-c251b.firebasestorage.app',
    iosBundleId: 'com.aselea.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwNMIr2ORfY-3xTdT7JxoKTrDw0FrsiA0',
    appId: '1:23625991695:ios:c619e15d3fc8d828e3c57a',
    messagingSenderId: '23625991695',
    projectId: 'hrms-app-c251b',
    storageBucket: 'hrms-app-c251b.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYWsNbc0I9_SqrO87yWkTPETpqtg3Efb0',
    appId: '1:23625991695:web:c4fa824e60ccf386e3c57a',
    messagingSenderId: '23625991695',
    projectId: 'hrms-app-c251b',
    authDomain: 'hrms-app-c251b.firebaseapp.com',
    storageBucket: 'hrms-app-c251b.firebasestorage.app',
    measurementId: 'G-JNJBFZD3LD',
  );
}
